
package view;

import controller.Project;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import model.ProjectModel;
import model.TaskModel;

/**
 *
 * @author RFagundes
 */



public class HomeScreen extends javax.swing.JFrame {

     ProjectModel projecModel;
     TaskModel taskModel;
     
     DefaultListModel projectController ;
    
    public HomeScreen() {
        initComponents();
        decorateTableTask();
        initDateController();
        initComponentsModel();
    }

    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeHeader = new javax.swing.JPanel();
        HomeHeaderLogo = new javax.swing.JLabel();
        HomeHeaderTitle = new javax.swing.JLabel();
        HomeHeaderSubtitle = new javax.swing.JLabel();
        containerProjects = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProjectList = new javax.swing.JList<>();
        HomeProject = new javax.swing.JLabel();
        HomeBtnAddProject = new javax.swing.JLabel();
        containerTasks = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TaskList = new javax.swing.JTable();
        HomeTask = new javax.swing.JLabel();
        HomeBtnAddTask = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));

        homeHeader.setBackground(new java.awt.Color(0, 0, 102));

        HomeHeaderLogo.setText("logo");

        HomeHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HomeHeaderTitle.setForeground(new java.awt.Color(0, 255, 255));
        HomeHeaderTitle.setText("Task Manager");

        HomeHeaderSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HomeHeaderSubtitle.setForeground(new java.awt.Color(51, 255, 255));
        HomeHeaderSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeHeaderSubtitle.setText("Gerencie projetos e tarefas");

        javax.swing.GroupLayout homeHeaderLayout = new javax.swing.GroupLayout(homeHeader);
        homeHeader.setLayout(homeHeaderLayout);
        homeHeaderLayout.setHorizontalGroup(
            homeHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeHeaderLayout.createSequentialGroup()
                        .addComponent(HomeHeaderLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HomeHeaderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(HomeHeaderSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeHeaderLayout.setVerticalGroup(
            homeHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeHeaderLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeHeaderTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(HomeHeaderSubtitle)
                .addContainerGap())
        );

        containerProjects.setBackground(new java.awt.Color(0, 0, 102));

        ProjectList.setBackground(new java.awt.Color(0, 204, 204));
        ProjectList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProjectList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProjectList.setForeground(new java.awt.Color(0, 0, 102));
        ProjectList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProjectList.setAutoscrolls(false);
        jScrollPane1.setViewportView(ProjectList);

        HomeProject.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HomeProject.setForeground(new java.awt.Color(51, 255, 153));
        HomeProject.setText("Projetos");

        HomeBtnAddProject.setText("btn");
        HomeBtnAddProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnAddProjectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout containerProjectsLayout = new javax.swing.GroupLayout(containerProjects);
        containerProjects.setLayout(containerProjectsLayout);
        containerProjectsLayout.setHorizontalGroup(
            containerProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerProjectsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(containerProjectsLayout.createSequentialGroup()
                        .addComponent(HomeProject, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HomeBtnAddProject, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        containerProjectsLayout.setVerticalGroup(
            containerProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerProjectsLayout.createSequentialGroup()
                .addGroup(containerProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeProject, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeBtnAddProject, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        containerTasks.setBackground(new java.awt.Color(0, 0, 102));

        TaskList.setBackground(new java.awt.Color(0, 51, 102));
        TaskList.setForeground(new java.awt.Color(0, 0, 102));
        TaskList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TaskList);

        HomeTask.setBackground(new java.awt.Color(0, 0, 102));
        HomeTask.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HomeTask.setForeground(new java.awt.Color(0, 255, 153));
        HomeTask.setText("Tarefas");

        HomeBtnAddTask.setText("btn");
        HomeBtnAddTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnAddTaskMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout containerTasksLayout = new javax.swing.GroupLayout(containerTasks);
        containerTasks.setLayout(containerTasksLayout);
        containerTasksLayout.setHorizontalGroup(
            containerTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeTask, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeBtnAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );
        containerTasksLayout.setVerticalGroup(
            containerTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeTask, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeBtnAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(containerProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(containerTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(containerTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void HomeBtnAddProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnAddProjectMouseClicked
       ProjectScreen projectScreen = new ProjectScreen(this, rootPaneCheckingEnabled);
       projectScreen.setVisible(true);
       
       projectScreen.addWindowListener(new WindowAdapter(){
       
              public void windowClosed(WindowEvent e){
                  loadProjects();
              }       
          });
    }//GEN-LAST:event_HomeBtnAddProjectMouseClicked

    
    
    
    private void HomeBtnAddTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnAddTaskMouseClicked
        TaskScreen taskScreen = new TaskScreen(this, rootPaneCheckingEnabled);
        taskScreen.setVisible(true);
    }//GEN-LAST:event_HomeBtnAddTaskMouseClicked

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeBtnAddProject;
    private javax.swing.JLabel HomeBtnAddTask;
    private javax.swing.JLabel HomeHeaderLogo;
    private javax.swing.JLabel HomeHeaderSubtitle;
    private javax.swing.JLabel HomeHeaderTitle;
    private javax.swing.JLabel HomeProject;
    private javax.swing.JLabel HomeTask;
    private javax.swing.JList<String> ProjectList;
    private javax.swing.JTable TaskList;
    private javax.swing.JPanel containerProjects;
    private javax.swing.JPanel containerTasks;
    private javax.swing.JPanel homeHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables


 public void decorateTableTask(){
     TaskList.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
     TaskList.getTableHeader().setBackground(new Color(0,0,102));
     TaskList.getTableHeader().setForeground(new Color(255,255,102));
         
     TaskList.setAutoCreateRowSorter(true);    
 }

 
 public void initDateController(){
     projecModel = new ProjectModel();
     taskModel   = new TaskModel();
 }

 
 public void initComponentsModel(){
     projectController = new DefaultListModel();
     loadProjects();
 }
 
 
 
 public void loadProjects(){
     List<Project> projects = projecModel.getAll();
     projectController.clear();
     
     for (int i = 0; i < projects.size(); i++) {
         
         Project project = projects.get(i);
         projectController.addElement(project);
     }
     
      ProjectList.setModel(projectController);
 }
 
 
 
}
